"""add_stayflow_domain_models

Revision ID: f519176e1f37
Revises: 001
Create Date: 2026-08-21 10:42:45.246324

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f519176e1f37'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comodidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('servicos_adicionais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('hoteis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_comodidade',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('comodidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comodidade_id'], ['comodidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotel_id', 'comodidade_id')
    )
    op.create_table('quartos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('capacidade_adultos', sa.Integer(), nullable=False),
    sa.Column('capacidade_criancas', sa.Integer(), nullable=False),
    sa.Column('preco_diaria', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarifas_temporada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('multiplicador', sa.Float(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quarto_id', sa.Integer(), nullable=False),
    sa.Column('checkin', sa.Date(), nullable=False),
    sa.Column('checkout', sa.Date(), nullable=False),
    sa.Column('num_adultos', sa.Integer(), nullable=False),
    sa.Column('num_criancas', sa.Integer(), nullable=False),
    sa.Column('num_bebes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tipo_tarifa', sa.String(length=20), nullable=False),
    sa.Column('early_checkin', sa.Boolean(), nullable=False),
    sa.Column('late_checkout', sa.Boolean(), nullable=False),
    sa.Column('berco', sa.Boolean(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id')
    )
    op.create_table('reserva_servico',
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_adicionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reserva_id', 'servico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_servico')
    op.drop_table('avaliacoes')
    op.drop_table('reservas')
    op.drop_table('tarifas_temporada')
    op.drop_table('quartos')
    op.drop_table('hotel_comodidade')
    op.drop_table('hoteis')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('servicos_adicionais')
    op.drop_table('comodidades')
    op.drop_table('cidades')
    # ### end Alembic commands ###
